services:
  #If you need replicas of the containers, copy and past. At this moment,
  #DockerComposeV2's "replica" does not work as DockerComposeV1's
  # frontend:
  #   container_name: ang
  #   build:
  #     context: ./ang
  #     dockerfile: ./Dockerfile
  # nginx:
  #   container_name: middlenginx
  #   image: nginx:stable-alpine
  #   expose:
  #     - "80"
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
  #   depends_on:
  #     - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
    command:
      make migrate

  localstack:
    container_name: localstack-main
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - volume-localstack:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"      

  db:
    container_name: postgres
    image: postgres:16.1
    volumes:
      - volume-postgres-test:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker

volumes:
    volume-postgres: {}
    volume-postgres-test: {}
    volume-localstack: {}
